-- CUSTOMER ANALYSIS SQL
-- ---------------------
-- SQL queries for customer, purchase, product, and revenue analysis.
-- Core concepts and query logic are kept the same.


-- ============================================================
-- 1. REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS
-- ============================================================

SELECT
    gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- ============================================================
-- 2. CUSTOMERS WHO USED A DISCOUNT BUT SPENT ABOVE AVERAGE
-- ============================================================

SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM customer
  );


-- ============================================================
-- 3. TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE RATING
-- ============================================================

SELECT
    item_purchased,
    ROUND(AVG(review_rating)::NUMERIC, 2) AS "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- ============================================================
-- 4. AVERAGE PURCHASE AMOUNT BY SHIPPING TYPE
--    (STANDARD VS EXPRESS)
-- ============================================================

SELECT
    shipping_type,
    ROUND(AVG(purchase_amount)::NUMERIC, 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- ============================================================
-- 5. DO SUBSCRIBED CUSTOMERS SPEND MORE?
--    COMPARE CUSTOMER COUNT, AVERAGE SPEND, AND TOTAL REVENUE
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id) AS total_customer,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;


-- ============================================================
-- 6. TOP 5 PRODUCTS WITH THE HIGHEST DISCOUNT RATE
-- ============================================================

SELECT
    item_purchased,
    (
        100 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*)
    ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ============================================================
-- 7. CUSTOMER SEGMENTATION
--    NEW, RETURNING, AND LOYAL CUSTOMERS
-- ============================================================

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS "Number of Customer"
FROM customer_type
GROUP BY customer_segment;


-- ============================================================
-- 8. TOP 3 PRODUCTS IN EACH CATEGORY
-- ============================================================

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- ============================================================
-- 9. ARE REPEAT BUYERS ALSO LIKELY TO SUBSCRIBE?
--    REPEAT BUYERS = MORE THAN 5 PREVIOUS PURCHASES
-- ============================================================

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- ============================================================
-- 10. REVENUE CONTRIBUTION BY AGE GROUP
-- ============================================================

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
